var searchData=
[
  ['c_20explique_20las_20operaciones_20que_20se_20pueden_20realizar_0',['5. Â¿Que es la memoria dinamica y como se gestiona en lenguajes de programacion como C++, explique las operaciones que se pueden realizar?',['../index.html#autotoc_md10',1,'']]],
  ['caracterä±sticas_1',['7. Explique que es un arbol binario y cuales son sus principales caracterÄ±sticas.',['../index.html#autotoc_md12',1,'']]],
  ['caracteristicas_20principales_2',['1. Â¿Que es un algoritmo y cuales son sus caracteristicas principales?',['../index.html#autotoc_md6',1,'']]],
  ['cola_20queue_20y_20en_20que_20situaciones_20se_20utiliza_20comunmente_3',['8. Â¿Que es una cola (queue) y en que situaciones se utiliza comunmente?',['../index.html#autotoc_md13',1,'']]],
  ['cola_20queue_20y_20una_20pila_20stack_4',['9. Â¿Cual es la diferencia entre una cola queue y una pila (stack)?',['../index.html#autotoc_md14',1,'']]],
  ['como_20funciona_20el_20algoritmo_20de_20insercion_20insert_20en_20una_20tabla_20hash_5',['10. Describe como funciona el algoritmo de insercion (insert) en una tabla hash.',['../index.html#autotoc_md15',1,'']]],
  ['como_20funciona_20el_20algoritmo_20de_20recorrido_20traversal_20en_20un_20arbol_20binario_6',['19. Explica como funciona el algoritmo de recorrido (traversal) en un arbol binario.',['../index.html#autotoc_md24',1,'']]],
  ['como_20funciona_20una_20lista_20enlazada_20y_20cuales_20son_20sus_20ventajas_20y_20desventajas_7',['15. Describe como funciona una lista enlazada y cuales son sus ventajas y desventajas.',['../index.html#autotoc_md20',1,'']]],
  ['como_20se_20gestiona_20en_20lenguajes_20de_20programacion_20como_20c_20explique_20las_20operaciones_20que_20se_20pueden_20realizar_8',['5. Â¿Que es la memoria dinamica y como se gestiona en lenguajes de programacion como C++, explique las operaciones que se pueden realizar?',['../index.html#autotoc_md10',1,'']]],
  ['como_20se_20realiza_20la_20operacion_20de_20insercion_20push_20en_20una_20pila_20stack_9',['13. Explica como se realiza la operacion de insercion (push) en una pila (stack).',['../index.html#autotoc_md18',1,'']]],
  ['comparacion_20con_20la_20memoria_20estatica_10',['6. Â¿Cuales son las ventajas y desventajas de la memoria dinamica en comparacion con la memoria estatica?',['../index.html#autotoc_md11',1,'']]],
  ['compilar_3a_11',['Compilar:',['../index.html#autotoc_md3',1,'']]],
  ['complejidad_20temporal_20de_20las_20operaciones_20de_20apilar_20push_20y_20desapilar_20pop_20en_20una_20pila_12',['14. Â¿Cual es la complejidad temporal de las operaciones de apilar (push) y desapilar (pop) en una pila?',['../index.html#autotoc_md19',1,'']]],
  ['complejidad_20temporal_20de_20los_20algoritmos_20proporciona_20un_20ejemplo_20de_20un_20algoritmo_20y_20determina_20su_20complejidad_20temporal_20utilizando_20ambas_20notaciones_20big_20o_20y_20omega_13',['21. Explique la diferencia entre la notacion Big O (O) y la notacion Omega () en el analisis de la complejidad temporal de los algoritmos. Proporciona un ejemplo de un algoritmo y determina su complejidad temporal utilizando ambas notaciones Big O y Omega.',['../index.html#autotoc_md26',1,'']]],
  ['complejidad_20temporal_20del_20recorrido_20en_20preorden_20en_20orden_20y_20en_20postorden_20en_20un_20arbol_20binario_20balanceado_14',['20. Â¿Cual es la complejidad temporal del recorrido en preorden, en orden y en postorden en un arbol binario balanceado?',['../index.html#autotoc_md25',1,'']]],
  ['complejidad_20temporal_20promedio_20de_20busqueda_20en_20una_20tabla_20hash_20bien_20implementada_15',['12. Â¿Cual es la complejidad temporal promedio de busqueda en una tabla hash bien implementada?',['../index.html#autotoc_md17',1,'']]],
  ['comunmente_16',['8. Â¿Que es una cola (queue) y en que situaciones se utiliza comunmente?',['../index.html#autotoc_md13',1,'']]],
  ['con_20la_20memoria_20estatica_17',['6. Â¿Cuales son las ventajas y desventajas de la memoria dinamica en comparacion con la memoria estatica?',['../index.html#autotoc_md11',1,'']]],
  ['contacto_18',['Contacto',['../struct_contacto.html',1,'']]],
  ['contacto_2ehpp_19',['Contacto.hpp',['../_contacto_8hpp.html',1,'']]],
  ['contactocloud_20',['ContactoCloud',['../struct_contacto_cloud.html',1,'']]],
  ['contactos_20en_20la_20nube_21',['Programa que simula un almacenamiento de contactos en la nube.',['../index.html#autotoc_md2',1,'']]],
  ['contiene_22',['16. Â¿Que es un nodo en una lista enlazada y que contiene?',['../index.html#autotoc_md21',1,'']]],
  ['cuales_20son_20sus_20caracteristicas_20principales_23',['1. Â¿Que es un algoritmo y cuales son sus caracteristicas principales?',['../index.html#autotoc_md6',1,'']]],
  ['cuales_20son_20sus_20principales_20caracterä±sticas_24',['7. Explique que es un arbol binario y cuales son sus principales caracterÄ±sticas.',['../index.html#autotoc_md12',1,'']]],
  ['cuales_20son_20sus_20ventajas_20y_20desventajas_25',['15. Describe como funciona una lista enlazada y cuales son sus ventajas y desventajas.',['../index.html#autotoc_md20',1,'']]]
];
