var searchData=
[
  ['un_20algoritmo_20eficiente_20y_20uno_20ineficiente_0',['2. Explica la diferencia entre un algoritmo eficiente y uno ineficiente.',['../index.html#autotoc_md7',1,'']]],
  ['un_20algoritmo_20y_20cuales_20son_20sus_20caracteristicas_20principales_1',['1. Â¿Que es un algoritmo y cuales son sus caracteristicas principales?',['../index.html#autotoc_md6',1,'']]],
  ['un_20almacenamiento_20de_20contactos_20en_20la_20nube_2',['Programa que simula un almacenamiento de contactos en la nube.',['../index.html#autotoc_md2',1,'']]],
  ['un_20arbol_20binario_3',['19. Explica como funciona el algoritmo de recorrido (traversal) en un arbol binario.',['../index.html#autotoc_md24',1,'']]],
  ['un_20arbol_20binario_20balanceado_4',['20. Â¿Cual es la complejidad temporal del recorrido en preorden, en orden y en postorden en un arbol binario balanceado?',['../index.html#autotoc_md25',1,'']]],
  ['un_20arbol_20binario_20y_20cuales_20son_20sus_20principales_20caracterä±sticas_5',['7. Explique que es un arbol binario y cuales son sus principales caracterÄ±sticas.',['../index.html#autotoc_md12',1,'']]],
  ['un_20ejemplo_20de_20un_20algoritmo_20y_20determina_20su_20complejidad_20temporal_20utilizando_20ambas_20notaciones_20big_20o_20y_20omega_6',['21. Explique la diferencia entre la notacion Big O (O) y la notacion Omega () en el analisis de la complejidad temporal de los algoritmos. Proporciona un ejemplo de un algoritmo y determina su complejidad temporal utilizando ambas notaciones Big O y Omega.',['../index.html#autotoc_md26',1,'']]],
  ['un_20nodo_20en_20una_20lista_20enlazada_7',['18. Â¿Como se realiza la eliminacion (delete) de un nodo en una lista enlazada?',['../index.html#autotoc_md23',1,'']]],
  ['un_20nodo_20en_20una_20lista_20enlazada_20y_20que_20contiene_8',['16. Â¿Que es un nodo en una lista enlazada y que contiene?',['../index.html#autotoc_md21',1,'']]],
  ['una_20cola_20queue_20y_20en_20que_20situaciones_20se_20utiliza_20comunmente_9',['8. Â¿Que es una cola (queue) y en que situaciones se utiliza comunmente?',['../index.html#autotoc_md13',1,'']]],
  ['una_20cola_20queue_20y_20una_20pila_20stack_10',['9. Â¿Cual es la diferencia entre una cola queue y una pila (stack)?',['../index.html#autotoc_md14',1,'']]],
  ['una_20estructura_20de_20datos_20estatica_20y_20una_20dinamica_11',['4. Describe las diferencias entre una estructura de datos estatica y una dinamica.',['../index.html#autotoc_md9',1,'']]],
  ['una_20estructura_20de_20datos_20y_20por_20que_20son_20importantes_12',['3. Â¿Que es una estructura de datos y por que son importantes?',['../index.html#autotoc_md8',1,'']]],
  ['una_20lista_20enlazada_13',['18. Â¿Como se realiza la eliminacion (delete) de un nodo en una lista enlazada?',['../index.html#autotoc_md23',1,'']]],
  ['una_20lista_20enlazada_20simple_20y_20una_20lista_20enlazada_20doblemente_20enlazada_14',['17. Â¿Cual es la diferencia entre una lista enlazada simple y una lista enlazada doblemente enlazada?',['../index.html#autotoc_md22',1,'']]],
  ['una_20lista_20enlazada_20y_20cuales_20son_20sus_20ventajas_20y_20desventajas_15',['15. Describe como funciona una lista enlazada y cuales son sus ventajas y desventajas.',['../index.html#autotoc_md20',1,'']]],
  ['una_20lista_20enlazada_20y_20que_20contiene_16',['16. Â¿Que es un nodo en una lista enlazada y que contiene?',['../index.html#autotoc_md21',1,'']]],
  ['una_20pila_17',['14. Â¿Cual es la complejidad temporal de las operaciones de apilar (push) y desapilar (pop) en una pila?',['../index.html#autotoc_md19',1,'']]],
  ['una_20pila_20stack_18',['13. Explica como se realiza la operacion de insercion (push) en una pila (stack).',['../index.html#autotoc_md18',1,'']]],
  ['una_20tabla_20hash_19',['10. Describe como funciona el algoritmo de insercion (insert) en una tabla hash.',['../index.html#autotoc_md15',1,'']]],
  ['una_20tabla_20hash_20bien_20implementada_20',['12. Â¿Cual es la complejidad temporal promedio de busqueda en una tabla hash bien implementada?',['../index.html#autotoc_md17',1,'']]],
  ['uno_20ineficiente_21',['2. Explica la diferencia entre un algoritmo eficiente y uno ineficiente.',['../index.html#autotoc_md7',1,'']]],
  ['utiliza_20comunmente_22',['8. Â¿Que es una cola (queue) y en que situaciones se utiliza comunmente?',['../index.html#autotoc_md13',1,'']]],
  ['utilizando_20ambas_20notaciones_20big_20o_20y_20omega_23',['21. Explique la diferencia entre la notacion Big O (O) y la notacion Omega () en el analisis de la complejidad temporal de los algoritmos. Proporciona un ejemplo de un algoritmo y determina su complejidad temporal utilizando ambas notaciones Big O y Omega.',['../index.html#autotoc_md26',1,'']]]
];
