-- Insertando informacion basica de los cursos a la tabla Cursos
INSERT INTO Cursos(Sigla, Nombre, Semestre, Creditos)
VALUES
    ('IE-0579','Administración de sistemas',1,4),
    ('IE-0613','Electrónica industrial',1,4),
    ('IE-0599','Anteproyecto de TFG',1,4),
    ('IE-0679','Ciencia de datos para la estimación y pronóstico de eventos',2,3),
    ('IE-0541','Seguridad ocupacional',2,3),
    ('IE-9500','Trabajo final de graduación',2,0),
    ('IE-0117','Programación bajo plataformas abiertas',NULL,3),
    ('IE-0217','Estructuras abstractas de datos y algoritmos para ingeniería',NULL,3),
    ('IE-0365','Transmisión de potencia',NULL,3),
    ('IE-0414','Control y simulación de convertidores electrónicos de potencia',NULL,3),
    ('IE-0417','Diseño de software para ingeniería',NULL,3),
    ('IE-0432','Laboratorio de control automatico',NULL,3),
    ('IE-0433','Instrumentación industrial',NULL,3),
    ('IE-0435','Inteligencia artificial aplicada a la ingeniería eléctrica',NULL,3),
    ('IE-0445','Metrología en la ingeniería eléctrica',NULL,3),
    ('IE-0447','Procesamiento digital de señales I',NULL,3),
    ('IE-0457','Conservación de energía eléctrica',NULL,3),
    ('IE-0461','Centrales y subestaciones',NULL,3),
    ('IE-0465','Redes de distribución y transmisión',NULL,3),
    ('IE-0467','Distribución eléctrica subterránea',NULL,3),
    ('IE-0469','Sistemas de potencia I',NULL,3),
    ('IE-0471','Diseño eléctrico industrial',NULL,3),
    ('IE-0505','Técnicas de optimización',NULL,3),
    ('IE-0509','Sistemas no lineales',NULL,3),
    ('IE-0514','Electrónica de potencia y control de máquinas',NULL,3),
    ('IE-0545','Mediciones ópticas',NULL,3),
    ('IE-0559','Energía solar fotovoltáica',NULL,3),
    ('IE-0563','Diseño de sistemas de iluminación',NULL,3),
    ('IE-0565','Ingeniería de alta tensión',NULL,3),
    ('IE-0569','Sistemas de potencia II',NULL,3),
    ('IE-0571','Diseño eléctrico industrial II',NULL,3),
    ('IE-0573','Diseño de sistemas de señales en edificaciones',NULL,3),
    ('IE-0614','Control e integración a la red de sistemas de generación eólica',NULL,3),
    ('IE-0619','Control eléctrico industrial',NULL,3),
    ('IE-0621','Verificación funcional del diseño de circuitos integrados',NULL,3),
    ('IE-0633','Automatización industrial',NULL,3),
    ('IE-0715','Máquinas eléctricas III',NULL,3),
    ('IE-0731','Sistemas en tiempo discreto',NULL,3),
    ('IE-0733','Control distribuido',NULL,3),
    ('IE-0769','Protección del sistema de potencia',NULL,3),
    ('IE-0869','Subestaciones',NULL,3),
    ('IE-1103','Temas especiales II en ingeniería',NULL,3),
    ('IE-1114','Temas especiales II en control',NULL,3),
    ('IE-1117','Temas especiales II en máquinas eléctricas',NULL,3),
    ('IE-1118','Temas especiales II en sistemas de potencia',NULL,3),
    ('IE-1169','Sobrevoltajes y coordinación de aislamiento',NULL,3),
    ('IE-0321','Estructuras de computadores digitales I',NULL,3),
    ('IE-0407','Electromagnetismo II',NULL,3),
    ('IE-0424','Laboratorio de circuitos digitales',NULL,3),
    ('IE-0437','Fotónica',NULL,3),
    ('IE-0439','Optoelectrónica',NULL,3),
    ('IE-0449','Visión por computador',NULL,3),
    ('IE-0521','Estructuras de computadoras digitales II',NULL,3),
    ('IE-0523','Circuitos digitales II',NULL,3),
    ('IE-0537','Radiometría y fotometría',NULL,3),
    ('IE-0623','Microprocesadores',NULL,3),
    ('IE-0624','Laboratorio de microcontroladores',NULL,3),
    ('IE-0724','Laboratorio de programación y microcomputadores',NULL,3),
    ('IE-1119','Temas especiales II en sistemas digitales',NULL,3),
    ('IE-0527','Ingeniería de comunicaciones',NULL,3),
    ('IE-0528','Laboratorio de transmisión de datos',NULL,3),
    ('IE-0529','Sistemas móviles en comunicaciones',NULL,3),
    ('IE-0530','Laboratorio de telecomunicaciones',NULL,3),
    ('IE-0539','Comunicaciones por fibra óptica',NULL,3),
    ('IE-0627','Conmutación telefónica',NULL,3),
    ('IE-0628','Laboratorio de microondas',NULL,3),
    ('IE-0629','Sistemas de comunicación',NULL,3),
    ('IE-0639','Circuitos integrados fotónicos',NULL,3),
    ('IE-0727','Ingeniería de radio',NULL,3),
    ('IE-0729','Redes telefónicas',NULL,3),
    ('IE-0739','Redes ópticas en telecomunicaciones',NULL,3),
    ('IE-0827','Sistemas de transmisión en telecomunicaciones',NULL,3),
    ('IE-0829','Teoría de tráfico',NULL,3),
    ('IE-1115','Temas especiales II en telecomunicaciones',NULL,3),
    ('IE-1116','Temas especiales II en electrónica',NULL,3);

-- Insertando cursos de bachillerato que son requisitos de cursos optativos
INSERT INTO Cursos(Sigla, Nombre, Semestre, Creditos)
VALUES
    ('IE-0247','Señales y Sistemas I',-1,3),
    ('IE-0307','Electromagnetismo I',-1,3),
    ('IE-0308','Laboratorio de Electrónica I',-1,3),
    ('IE-0315','Máquinas Eléctricas I',-1,4),
    ('IE-0316','Laboratorio de Máquinas Eléctricas I',-1,1),
    ('IE-0323','Circuitos Digitales I',-1,3),
    ('IE-0347','Señales y sistemas II',-1,3),
    ('IE-0405','Modelos Probabilísticos de Señales y Sistemas',-1,3),
    ('IE-0408','Laboratorio de Electrónica II',-1,3),
    ('IE-0413','Electrónica II',-1,3),
    ('IE-0431','Sistemas de Control',-1,3),
    ('IE-0479','Ingeniería Económica',-1,3),
    ('IE-0499','Proyecto Eléctrico',-1,3),
    ('IE-0501','Responsabilidades en el Ejercicio Profesional de la Ingeniería Eléctrica',-1,1),
    ('IE-0615','Máquinas Eléctricas II',-1,4),
    ('IE-0616','Laboratorio de Máquinas Eléctricas II',-1,1);

-- Insertando los requisitos entre cursos
INSERT INTO Requisitos(CursoID, RequisitoCursoID)
VALUES
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0579'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0479')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0613'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0413')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0613'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0315')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0599'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0599')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0679'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0405')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0679'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0579')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0541'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0501')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-9500'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0599')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0217'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0117')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0414'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0431')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0417'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0217')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0432'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0431')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0433'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0431')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0435'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0347')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0445'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0307')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0445'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0308')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0447'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0347')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0447'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0413')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0457'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0315')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0457'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0316')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0461'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0615')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0461'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0616')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0465'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0365')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0467'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0307')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0467'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0315')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0467'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0316')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0469'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0365')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0469'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0615')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0469'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0616')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0471'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0315')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0471'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0316')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0505'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0347')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0509'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0431')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0514'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0413')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0514'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0315')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0514'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0316')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0545'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0307')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0545'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0308')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0559'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0315')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0559'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0316')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0563'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0471')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0565'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0469')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0569'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0469')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0571'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0471')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0573'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0471')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0614'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0431')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0614'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0615')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0614'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0616')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0619'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0323')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0619'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0615')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0619'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0616')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0621'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0523')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0633'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0323')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0633'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0431')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0715'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0615')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0715'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0616')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0731'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0431')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0733'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0431')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0769'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0365')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0869'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0365')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-1103'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0499')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-1114'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0431')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-1117'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0615')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-1117'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0616')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-1118'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0365')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-1169'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0365')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0407'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0307')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0424'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0308')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0424'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0321')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0424'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0523')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0437'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0307')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0437'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0308')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0439'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0307')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0439'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0308')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0449'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0247')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0521'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0321')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0523'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0323')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0537'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0307')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0537'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0308')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0623'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0321')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0624'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0308')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0624'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0323')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0624'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0413')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0724'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0321')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-1119'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0321')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0527'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0307')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0527'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0405')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0528'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0527')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0529'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0527')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0530'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0527')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0539'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0307')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0539'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0308')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0627'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0527')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0628'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0307')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0628'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0408')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0629'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0527')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0639'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0307')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0639'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0308')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0727'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0527')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0729'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0527')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0739'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0307')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0739'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0308')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0827'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0527')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0829'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0527')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-1115'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0527')),
    ((SELECT CursoID FROM Cursos WHERE Sigla = 'IE-1116'),(SELECT CursoID FROM Cursos WHERE Sigla = 'IE-0413'));