var searchData=
[
  ['macros_20variables_20en_20un_20makefile_0',['13. Explique el proposito de las macros (variables) en un Makefile.',['../index.html#autotoc_md17',1,'']]],
  ['makefile_1',['Makefile',['../index.html#autotoc_md26',1,'1. Â¿Que suelen contener las variables CC, CFLAGS, CXXFLAGS y LDFLAGS en un makefile?'],['../index.html#autotoc_md16',1,'12. Â¿Cual es la diferencia entre una regla implicita y una regla explicita en un Makefile?'],['../index.html#autotoc_md17',1,'13. Explique el proposito de las macros (variables) en un Makefile.'],['../index.html#autotoc_md20',1,'16. Â¿Como se pueden definir dependencias entre los archivos fuente en un Makefile?'],['../index.html#autotoc_md21',1,'17. Explique como se puede compilar un proyecto en diferentes sistemas operativos usando un solo Makefile.'],['../index.html#autotoc_md22',1,'18. Â¿Cual es el proposito de los comandos clean y all en un Makefile?'],['../index.html#autotoc_md23',1,'19. Describa como se pueden pasar argumentos desde la linea de comandos a un Makefile.'],['../index.html#autotoc_md27',1,'2. Â¿De que se compone una regla en un Makefile?'],['../index.html#autotoc_md31',1,'6. Â¿Que utilidad tiene un @ en un Makefile?'],['../index.html#autotoc_md32',1,'7. Â¿Para que se utiliza .PHONY en un Makefile?'],['../index.html#autotoc_md25',1,'Parte Teorica - Makefile']]],
  ['makefile_20â¿que_20utilidad_20tienen_2',['5. Â¿Como se definen y se utilizan las variables en un Makefile? Â¿Que utilidad tienen?',['../index.html#autotoc_md30',1,'']]],
  ['makefile_20que_20compile_20un_20archivo_20fuente_20cpp_20a_20un_20archivoâ objetoâ _20o_3',['20. Proporcione un ejemplo de una regla en un Makefile que compile un archivo fuente .cpp a un archivoÂ objetoÂ .o.',['../index.html#autotoc_md24',1,'']]],
  ['makefile_20y_20como_20se_20define_4',['14. Â¿Que es un objetivo (target) en un Makefile y como se define?',['../index.html#autotoc_md18',1,'']]],
  ['makefile_20y_20cual_20es_20su_20funcion_20en_20un_20proyecto_20de_20c_5',['11. Â¿Que es un Makefile y cual es su funcion en un proyecto de C++?',['../index.html#autotoc_md15',1,'']]],
  ['makefiles_20en_20este_20enfoque_6',['15. Â¿Por que es util dividir un proyecto de C++ en multiples archivos fuente y como ayuda el uso de Makefiles en este enfoque?',['../index.html#autotoc_md19',1,'']]],
  ['modificador_20_24_20en_20una_20expresion_20regular_7',['8. Â¿Cual es el proposito del modificador $ en una expresion regular?',['../index.html#autotoc_md12',1,'']]],
  ['multiples_20archivos_20fuente_20y_20como_20ayuda_20el_20uso_20de_20makefiles_20en_20este_20enfoque_8',['15. Â¿Por que es util dividir un proyecto de C++ en multiples archivos fuente y como ayuda el uso de Makefiles en este enfoque?',['../index.html#autotoc_md19',1,'']]]
];
