var searchData=
[
  ['regla_20en_20un_20makefile_0',['2. Â¿De que se compone una regla en un Makefile?',['../index.html#autotoc_md27',1,'']]],
  ['regla_20en_20un_20makefile_20que_20compile_20un_20archivo_20fuente_20cpp_20a_20un_20archivoâ objetoâ _20o_1',['20. Proporcione un ejemplo de una regla en un Makefile que compile un archivo fuente .cpp a un archivoÂ objetoÂ .o.',['../index.html#autotoc_md24',1,'']]],
  ['regla_20implicita_20y_20una_20regla_20explicita_20en_20un_20makefile_2',['12. Â¿Cual es la diferencia entre una regla implicita y una regla explicita en un Makefile?',['../index.html#autotoc_md16',1,'']]],
  ['regular_3',['Regular',['../index.html#autotoc_md6',1,'2.  Â¿Que significan los caracteres especiales . y * en una expresion regular?'],['../index.html#autotoc_md7',1,'3. Â¿Como se pueden agrupar subexpresiones en una expresion regular?'],['../index.html#autotoc_md8',1,'4. Â¿Que funcion cumple la barra invertida \ en una expresion regular?'],['../index.html#autotoc_md9',1,'5. Explique como se pueden capturar coincidencias usando parentesis en una expresion regular.'],['../index.html#autotoc_md10',1,'6. Â¿Cual es la diferencia entre \d y \D en una expresion regular?'],['../index.html#autotoc_md11',1,'7. Â¿Como se representa una clase de caracteres en una expresion regular?'],['../index.html#autotoc_md12',1,'8. Â¿Cual es el proposito del modificador $ en una expresion regular?']]],
  ['regular_20compleja_20especialmente_20en_20contextos_20donde_20el_20tiempo_20de_20ejecucion_20es_20critico_4',['10. Discuta las implicaciones de rendimiento de utilizar expresiones regulares en aplicaciones de software. Â¿Que tecnicas se pueden aplicar para optimizar una expresion regular compleja, especialmente en contextos donde el tiempo de ejecucion es critico?',['../index.html#autotoc_md14',1,'']]],
  ['regular_20y_20cual_20es_20su_20proposito_20en_20programacion_5',['1.  Â¿Que es una expresion regular y cual es su proposito en programacion?',['../index.html#autotoc_md5',1,'']]],
  ['regulares_6',['Parte Teorica - Expresiones regulares',['../index.html#autotoc_md4',1,'']]],
  ['regulares_20en_20aplicaciones_20de_20software_20â¿que_20tecnicas_20se_20pueden_20aplicar_20para_20optimizar_20una_20expresion_20regular_20compleja_20especialmente_20en_20contextos_20donde_20el_20tiempo_20de_20ejecucion_20es_20critico_7',['10. Discuta las implicaciones de rendimiento de utilizar expresiones regulares en aplicaciones de software. Â¿Que tecnicas se pueden aplicar para optimizar una expresion regular compleja, especialmente en contextos donde el tiempo de ejecucion es critico?',['../index.html#autotoc_md14',1,'']]],
  ['regulares_20en_20c_8',['9. Describa como validar una direccion de correo electronico usando expresiones regulares en C++.',['../index.html#autotoc_md13',1,'']]],
  ['relaciona_20con_20sus_20prerequisitos_9',['3. Defina que es un target y como se relaciona con sus prerequisitos.',['../index.html#autotoc_md28',1,'']]],
  ['rendimiento_20de_20utilizar_20expresiones_20regulares_20en_20aplicaciones_20de_20software_20â¿que_20tecnicas_20se_20pueden_20aplicar_20para_20optimizar_20una_20expresion_20regular_20compleja_20especialmente_20en_20contextos_20donde_20el_20tiempo_20de_20ejecucion_20es_20critico_10',['10. Discuta las implicaciones de rendimiento de utilizar expresiones regulares en aplicaciones de software. Â¿Que tecnicas se pueden aplicar para optimizar una expresion regular compleja, especialmente en contextos donde el tiempo de ejecucion es critico?',['../index.html#autotoc_md14',1,'']]],
  ['representa_20una_20clase_20de_20caracteres_20en_20una_20expresion_20regular_11',['7. Â¿Como se representa una clase de caracteres en una expresion regular?',['../index.html#autotoc_md11',1,'']]]
];
