var searchData=
[
  ['c_0',['C',['../index.html#autotoc_md15',1,'11. Â¿Que es un Makefile y cual es su funcion en un proyecto de C++?'],['../index.html#autotoc_md13',1,'9. Describa como validar una direccion de correo electronico usando expresiones regulares en C++.']]],
  ['c_20en_20multiples_20archivos_20fuente_20y_20como_20ayuda_20el_20uso_20de_20makefiles_20en_20este_20enfoque_1',['15. Â¿Por que es util dividir un proyecto de C++ en multiples archivos fuente y como ayuda el uso de Makefiles en este enfoque?',['../index.html#autotoc_md19',1,'']]],
  ['c_20y_20o_20del_20compilador_20gcc_2',['4. Â¿Para que se utiliza la bandera-I,-c y-o del compilador gcc?',['../index.html#autotoc_md29',1,'']]],
  ['capturar_20coincidencias_20usando_20parentesis_20en_20una_20expresion_20regular_3',['5. Explique como se pueden capturar coincidencias usando parentesis en una expresion regular.',['../index.html#autotoc_md9',1,'']]],
  ['caracteres_20en_20una_20expresion_20regular_4',['7. Â¿Como se representa una clase de caracteres en una expresion regular?',['../index.html#autotoc_md11',1,'']]],
  ['caracteres_20especiales_20y_20en_20una_20expresion_20regular_5',['2.  Â¿Que significan los caracteres especiales . y * en una expresion regular?',['../index.html#autotoc_md6',1,'']]],
  ['cc_20cflags_20cxxflags_20y_20ldflags_20en_20un_20makefile_6',['1. Â¿Que suelen contener las variables CC, CFLAGS, CXXFLAGS y LDFLAGS en un makefile?',['../index.html#autotoc_md26',1,'']]],
  ['cflags_20cxxflags_20y_20ldflags_20en_20un_20makefile_7',['1. Â¿Que suelen contener las variables CC, CFLAGS, CXXFLAGS y LDFLAGS en un makefile?',['../index.html#autotoc_md26',1,'']]],
  ['clase_20de_20caracteres_20en_20una_20expresion_20regular_8',['7. Â¿Como se representa una clase de caracteres en una expresion regular?',['../index.html#autotoc_md11',1,'']]],
  ['clean_20y_20all_20en_20un_20makefile_9',['18. Â¿Cual es el proposito de los comandos clean y all en un Makefile?',['../index.html#autotoc_md22',1,'']]],
  ['coincidencias_20usando_20parentesis_20en_20una_20expresion_20regular_10',['5. Explique como se pueden capturar coincidencias usando parentesis en una expresion regular.',['../index.html#autotoc_md9',1,'']]],
  ['comandos_20a_20un_20makefile_11',['19. Describa como se pueden pasar argumentos desde la linea de comandos a un Makefile.',['../index.html#autotoc_md23',1,'']]],
  ['comandos_20clean_20y_20all_20en_20un_20makefile_12',['18. Â¿Cual es el proposito de los comandos clean y all en un Makefile?',['../index.html#autotoc_md22',1,'']]],
  ['como_20ayuda_20el_20uso_20de_20makefiles_20en_20este_20enfoque_13',['15. Â¿Por que es util dividir un proyecto de C++ en multiples archivos fuente y como ayuda el uso de Makefiles en este enfoque?',['../index.html#autotoc_md19',1,'']]],
  ['como_20se_20define_14',['14. Â¿Que es un objetivo (target) en un Makefile y como se define?',['../index.html#autotoc_md18',1,'']]],
  ['como_20se_20puede_20compilar_20un_20proyecto_20en_20diferentes_20sistemas_20operativos_20usando_20un_20solo_20makefile_15',['17. Explique como se puede compilar un proyecto en diferentes sistemas operativos usando un solo Makefile.',['../index.html#autotoc_md21',1,'']]],
  ['como_20se_20pueden_20capturar_20coincidencias_20usando_20parentesis_20en_20una_20expresion_20regular_16',['5. Explique como se pueden capturar coincidencias usando parentesis en una expresion regular.',['../index.html#autotoc_md9',1,'']]],
  ['como_20se_20pueden_20pasar_20argumentos_20desde_20la_20linea_20de_20comandos_20a_20un_20makefile_17',['19. Describa como se pueden pasar argumentos desde la linea de comandos a un Makefile.',['../index.html#autotoc_md23',1,'']]],
  ['como_20se_20relaciona_20con_20sus_20prerequisitos_18',['3. Defina que es un target y como se relaciona con sus prerequisitos.',['../index.html#autotoc_md28',1,'']]],
  ['como_20validar_20una_20direccion_20de_20correo_20electronico_20usando_20expresiones_20regulares_20en_20c_19',['9. Describa como validar una direccion de correo electronico usando expresiones regulares en C++.',['../index.html#autotoc_md13',1,'']]],
  ['compilacion_20y_20ejecucion_20',['Compilacion y ejecucion',['../index.html#autotoc_md2',1,'']]],
  ['compilador_20gcc_21',['4. Â¿Para que se utiliza la bandera-I,-c y-o del compilador gcc?',['../index.html#autotoc_md29',1,'']]],
  ['compilar_20un_20proyecto_20en_20diferentes_20sistemas_20operativos_20usando_20un_20solo_20makefile_22',['17. Explique como se puede compilar un proyecto en diferentes sistemas operativos usando un solo Makefile.',['../index.html#autotoc_md21',1,'']]],
  ['compile_20un_20archivo_20fuente_20cpp_20a_20un_20archivoâ objetoâ _20o_23',['20. Proporcione un ejemplo de una regla en un Makefile que compile un archivo fuente .cpp a un archivoÂ objetoÂ .o.',['../index.html#autotoc_md24',1,'']]],
  ['compleja_20especialmente_20en_20contextos_20donde_20el_20tiempo_20de_20ejecucion_20es_20critico_24',['10. Discuta las implicaciones de rendimiento de utilizar expresiones regulares en aplicaciones de software. Â¿Que tecnicas se pueden aplicar para optimizar una expresion regular compleja, especialmente en contextos donde el tiempo de ejecucion es critico?',['../index.html#autotoc_md14',1,'']]],
  ['compone_20una_20regla_20en_20un_20makefile_25',['2. Â¿De que se compone una regla en un Makefile?',['../index.html#autotoc_md27',1,'']]],
  ['con_20sus_20prerequisitos_26',['3. Defina que es un target y como se relaciona con sus prerequisitos.',['../index.html#autotoc_md28',1,'']]],
  ['contener_20las_20variables_20cc_20cflags_20cxxflags_20y_20ldflags_20en_20un_20makefile_27',['1. Â¿Que suelen contener las variables CC, CFLAGS, CXXFLAGS y LDFLAGS en un makefile?',['../index.html#autotoc_md26',1,'']]],
  ['contextos_20donde_20el_20tiempo_20de_20ejecucion_20es_20critico_28',['10. Discuta las implicaciones de rendimiento de utilizar expresiones regulares en aplicaciones de software. Â¿Que tecnicas se pueden aplicar para optimizar una expresion regular compleja, especialmente en contextos donde el tiempo de ejecucion es critico?',['../index.html#autotoc_md14',1,'']]],
  ['correo_20electronico_29',['Programa que valida el formato de un correo electronico.',['../index.html#autotoc_md1',1,'']]],
  ['correo_20electronico_20usando_20expresiones_20regulares_20en_20c_30',['9. Describa como validar una direccion de correo electronico usando expresiones regulares en C++.',['../index.html#autotoc_md13',1,'']]],
  ['cpp_20a_20un_20archivoâ objetoâ _20o_31',['20. Proporcione un ejemplo de una regla en un Makefile que compile un archivo fuente .cpp a un archivoÂ objetoÂ .o.',['../index.html#autotoc_md24',1,'']]],
  ['critico_32',['10. Discuta las implicaciones de rendimiento de utilizar expresiones regulares en aplicaciones de software. Â¿Que tecnicas se pueden aplicar para optimizar una expresion regular compleja, especialmente en contextos donde el tiempo de ejecucion es critico?',['../index.html#autotoc_md14',1,'']]],
  ['cual_20es_20su_20funcion_20en_20un_20proyecto_20de_20c_33',['11. Â¿Que es un Makefile y cual es su funcion en un proyecto de C++?',['../index.html#autotoc_md15',1,'']]],
  ['cual_20es_20su_20proposito_20en_20programacion_34',['1.  Â¿Que es una expresion regular y cual es su proposito en programacion?',['../index.html#autotoc_md5',1,'']]],
  ['cumple_20la_20barra_20invertida_20en_20una_20expresion_20regular_35',['4. Â¿Que funcion cumple la barra invertida \ en una expresion regular?',['../index.html#autotoc_md8',1,'']]],
  ['cxxflags_20y_20ldflags_20en_20un_20makefile_36',['1. Â¿Que suelen contener las variables CC, CFLAGS, CXXFLAGS y LDFLAGS en un makefile?',['../index.html#autotoc_md26',1,'']]]
];
